version: '3.7'

services:
  postgres_db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5432:5432
  web:
    build: ./app
    container_name: django_web
    command: bash -c "python manage.py migrate && python manage.py loadfixtures && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/code
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - postgres_db
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data: